### ISSUE TITLE
Powershell X68 / X64 

### ISSUE THREAD

**Issue by Josverl** [Jaykul/Jupyter-PowerShell#16]
HI , 
If I try to load a powershell module then I run into the below issue 

```
import-module : The current processor architecture is: X86.  
The module 'C:\Users\josverl\OneDrive -     Microsoft\WindowsPowerShell\Modules\AzureAD\2.0.0.131\AzureAD.psd1' 
requires the following architecture: Amd64.
```

What would it take to run an x64 Powershell kernel ?

**Comment by Josverl** [comment]
after some experimentation I find that if I build the solution using 
    dotnet build -r net462-x64

that the result is a working X64 Powershell on Windows.
sadly this cases the Powershell Core build to fail with 
'Project is targeting runtime 'net462-x64' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core'
which makes sanse as that runtime really does not make sense for .Net Core 

Im still trying to understand the build setup to understand what needs to be done to specify the x64 in the solution project files, to allow both build correctly, or to add both -x68 and x64 builds for the full powershell.

**Comment by Jaykul** [comment]
Yeah, you need `-r win7-x64` now, since I've switched to using NetCoreApp only

To be honest, you should be able to just run `build.ps1 -platform Windows` or whatever.

P.S. Although I'd like to support "Windows PowerShell" again at some point, due to the complexity of building a working PowerShell Core version, I've completely removed the "Windows PowerShell" support for now.
